# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1081, 892)
        self.displayBox = QtWidgets.QTextBrowser(Form)
        self.displayBox.setGeometry(QtCore.QRect(20, 110, 256, 761))
        self.displayBox.setObjectName("displayBox")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 80, 1121, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(290, 90, 20, 801))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(390, 100, 54, 12))
        self.label.setObjectName("label")
        self.coachName = QtWidgets.QLineEdit(Form)
        self.coachName.setGeometry(QtCore.QRect(400, 120, 113, 20))
        self.coachName.setObjectName("coachName")
        self.coachNum = QtWidgets.QLineEdit(Form)
        self.coachNum.setGeometry(QtCore.QRect(400, 160, 113, 20))
        self.coachNum.setObjectName("coachNum")
        self.addCoachButton = QtWidgets.QPushButton(Form)
        self.addCoachButton.setGeometry(QtCore.QRect(380, 210, 75, 23))
        self.addCoachButton.setObjectName("addCoachButton")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(340, 120, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(340, 160, 54, 12))
        self.label_3.setObjectName("label_3")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(530, 90, 20, 801))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.stdNum = QtWidgets.QLineEdit(Form)
        self.stdNum.setGeometry(QtCore.QRect(400, 340, 113, 20))
        self.stdNum.setText("")
        self.stdNum.setObjectName("stdNum")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(390, 280, 54, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(340, 300, 54, 12))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(340, 340, 54, 12))
        self.label_6.setObjectName("label_6")
        self.addStdButton = QtWidgets.QPushButton(Form)
        self.addStdButton.setGeometry(QtCore.QRect(380, 390, 75, 23))
        self.addStdButton.setObjectName("addStdButton")
        self.stdName = QtWidgets.QLineEdit(Form)
        self.stdName.setGeometry(QtCore.QRect(400, 300, 113, 20))
        self.stdName.setText("")
        self.stdName.setObjectName("stdName")
        self.fieldLocation = QtWidgets.QLineEdit(Form)
        self.fieldLocation.setGeometry(QtCore.QRect(400, 520, 113, 20))
        self.fieldLocation.setObjectName("fieldLocation")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(390, 460, 54, 12))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(340, 480, 54, 12))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(340, 520, 54, 12))
        self.label_9.setObjectName("label_9")
        self.fieldNum = QtWidgets.QLineEdit(Form)
        self.fieldNum.setGeometry(QtCore.QRect(400, 480, 113, 20))
        self.fieldNum.setObjectName("fieldNum")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(340, 560, 54, 12))
        self.label_10.setObjectName("label_10")
        self.fieldCapacity = QtWidgets.QLineEdit(Form)
        self.fieldCapacity.setGeometry(QtCore.QRect(400, 560, 113, 20))
        self.fieldCapacity.setObjectName("fieldCapacity")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(340, 710, 54, 12))
        self.label_11.setObjectName("label_11")
        self.examDate = QtWidgets.QLineEdit(Form)
        self.examDate.setGeometry(QtCore.QRect(400, 790, 113, 20))
        self.examDate.setObjectName("examDate")
        self.examField = QtWidgets.QLineEdit(Form)
        self.examField.setGeometry(QtCore.QRect(400, 750, 113, 20))
        self.examField.setObjectName("examField")
        self.addExamButton = QtWidgets.QPushButton(Form)
        self.addExamButton.setGeometry(QtCore.QRect(380, 840, 75, 23))
        self.addExamButton.setObjectName("addExamButton")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(340, 750, 54, 12))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(390, 690, 54, 12))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(340, 790, 54, 12))
        self.label_14.setObjectName("label_14")
        self.examNum = QtWidgets.QLineEdit(Form)
        self.examNum.setGeometry(QtCore.QRect(400, 710, 113, 20))
        self.examNum.setObjectName("examNum")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(530, 90, 20, 801))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(770, 90, 20, 801))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.lessCoach = QtWidgets.QLineEdit(Form)
        self.lessCoach.setGeometry(QtCore.QRect(640, 790, 113, 20))
        self.lessCoach.setObjectName("lessCoach")
        self.lessLessNum = QtWidgets.QLineEdit(Form)
        self.lessLessNum.setGeometry(QtCore.QRect(640, 340, 113, 20))
        self.lessLessNum.setText("")
        self.lessLessNum.setObjectName("lessLessNum")
        self.presClassButton = QtWidgets.QPushButton(Form)
        self.presClassButton.setGeometry(QtCore.QRect(620, 390, 75, 23))
        self.presClassButton.setObjectName("presClassButton")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(630, 280, 54, 12))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(580, 480, 54, 12))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(580, 710, 54, 12))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(630, 100, 54, 12))
        self.label_18.setObjectName("label_18")
        self.lessStdNum = QtWidgets.QLineEdit(Form)
        self.lessStdNum.setGeometry(QtCore.QRect(640, 300, 113, 20))
        self.lessStdNum.setText("")
        self.lessStdNum.setObjectName("lessStdNum")
        self.presExamButton = QtWidgets.QPushButton(Form)
        self.presExamButton.setGeometry(QtCore.QRect(620, 210, 75, 23))
        self.presExamButton.setObjectName("presExamButton")
        self.examExamNum = QtWidgets.QLineEdit(Form)
        self.examExamNum.setGeometry(QtCore.QRect(640, 160, 113, 20))
        self.examExamNum.setObjectName("examExamNum")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(580, 340, 54, 12))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(580, 520, 54, 12))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(580, 560, 54, 12))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(580, 750, 54, 12))
        self.label_22.setObjectName("label_22")
        self.examStdNum = QtWidgets.QLineEdit(Form)
        self.examStdNum.setGeometry(QtCore.QRect(640, 120, 113, 20))
        self.examStdNum.setObjectName("examStdNum")
        self.fieldFieldNum = QtWidgets.QLineEdit(Form)
        self.fieldFieldNum.setGeometry(QtCore.QRect(640, 520, 113, 20))
        self.fieldFieldNum.setObjectName("fieldFieldNum")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(580, 300, 54, 12))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(580, 790, 54, 12))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(630, 460, 54, 12))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(580, 120, 54, 12))
        self.label_26.setObjectName("label_26")
        self.presFieldButton = QtWidgets.QPushButton(Form)
        self.presFieldButton.setGeometry(QtCore.QRect(620, 610, 75, 23))
        self.presFieldButton.setObjectName("presFieldButton")
        self.addLessButton = QtWidgets.QPushButton(Form)
        self.addLessButton.setGeometry(QtCore.QRect(620, 840, 75, 23))
        self.addLessButton.setObjectName("addLessButton")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(580, 160, 54, 12))
        self.label_27.setObjectName("label_27")
        self.fieldTime = QtWidgets.QLineEdit(Form)
        self.fieldTime.setGeometry(QtCore.QRect(640, 560, 113, 20))
        self.fieldTime.setObjectName("fieldTime")
        self.fieldStdNum = QtWidgets.QLineEdit(Form)
        self.fieldStdNum.setGeometry(QtCore.QRect(640, 480, 113, 20))
        self.fieldStdNum.setObjectName("fieldStdNum")
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setGeometry(QtCore.QRect(630, 690, 54, 12))
        self.label_28.setObjectName("label_28")
        self.lessNum = QtWidgets.QLineEdit(Form)
        self.lessNum.setGeometry(QtCore.QRect(640, 710, 113, 20))
        self.lessNum.setObjectName("lessNum")
        self.lessField = QtWidgets.QLineEdit(Form)
        self.lessField.setGeometry(QtCore.QRect(640, 750, 113, 20))
        self.lessField.setObjectName("lessField")
        self.line_6 = QtWidgets.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(300, 250, 241, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(Form)
        self.line_7.setGeometry(QtCore.QRect(300, 430, 241, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(Form)
        self.line_8.setGeometry(QtCore.QRect(300, 650, 241, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(Form)
        self.line_9.setGeometry(QtCore.QRect(540, 650, 241, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(Form)
        self.line_10.setGeometry(QtCore.QRect(540, 430, 241, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(Form)
        self.line_11.setGeometry(QtCore.QRect(540, 250, 241, 16))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(Form)
        self.line_12.setGeometry(QtCore.QRect(780, 650, 301, 16))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setGeometry(QtCore.QRect(910, 690, 54, 12))
        self.label_29.setObjectName("label_29")
        self.hahaha = QtWidgets.QLineEdit(Form)
        self.hahaha.setGeometry(QtCore.QRect(860, 710, 113, 20))
        self.hahaha.setObjectName("hahaha")
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setGeometry(QtCore.QRect(800, 710, 54, 16))
        self.label_30.setObjectName("label_30")
        self.consult = QtWidgets.QPushButton(Form)
        self.consult.setGeometry(QtCore.QRect(990, 710, 75, 23))
        self.consult.setObjectName("consult")
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setGeometry(QtCore.QRect(800, 750, 54, 16))
        self.label_31.setObjectName("label_31")
        self.lalala = QtWidgets.QLineEdit(Form)
        self.lalala.setGeometry(QtCore.QRect(860, 750, 113, 20))
        self.lalala.setText("")
        self.lalala.setObjectName("lalala")
        self.cancel = QtWidgets.QPushButton(Form)
        self.cancel.setGeometry(QtCore.QRect(990, 750, 75, 23))
        self.cancel.setObjectName("cancel")
        self.label_32 = QtWidgets.QLabel(Form)
        self.label_32.setGeometry(QtCore.QRect(370, 30, 401, 41))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(Form)
        self.label_33.setGeometry(QtCore.QRect(800, 840, 241, 16))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(Form)
        self.label_34.setGeometry(QtCore.QRect(800, 860, 191, 16))
        self.label_34.setObjectName("label_34")
        self.addFieldButton = QtWidgets.QPushButton(Form)
        self.addFieldButton.setGeometry(QtCore.QRect(380, 600, 75, 23))
        self.addFieldButton.setObjectName("addFieldButton")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(840, 90, 191, 551))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dispCoach = QtWidgets.QPushButton(self.widget)
        self.dispCoach.setObjectName("dispCoach")
        self.verticalLayout.addWidget(self.dispCoach)
        self.dispStd = QtWidgets.QPushButton(self.widget)
        self.dispStd.setObjectName("dispStd")
        self.verticalLayout.addWidget(self.dispStd)
        self.dispLess = QtWidgets.QPushButton(self.widget)
        self.dispLess.setObjectName("dispLess")
        self.verticalLayout.addWidget(self.dispLess)
        self.dispExam = QtWidgets.QPushButton(self.widget)
        self.dispExam.setObjectName("dispExam")
        self.verticalLayout.addWidget(self.dispExam)
        self.dispField = QtWidgets.QPushButton(self.widget)
        self.dispField.setObjectName("dispField")
        self.verticalLayout.addWidget(self.dispField)
        self.dispBatchLess = QtWidgets.QPushButton(self.widget)
        self.dispBatchLess.setObjectName("dispBatchLess")
        self.verticalLayout.addWidget(self.dispBatchLess)
        self.dispBatchExam = QtWidgets.QPushButton(self.widget)
        self.dispBatchExam.setObjectName("dispBatchExam")
        self.verticalLayout.addWidget(self.dispBatchExam)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "添加教练"))
        self.addCoachButton.setText(_translate("Form", "确认添加"))
        self.label_2.setText(_translate("Form", "教练姓名"))
        self.label_3.setText(_translate("Form", "教练编号"))
        self.label_4.setText(_translate("Form", "添加学员"))
        self.label_5.setText(_translate("Form", "学员姓名"))
        self.label_6.setText(_translate("Form", "学员编号"))
        self.addStdButton.setText(_translate("Form", "确认添加"))
        self.label_7.setText(_translate("Form", "添加场地"))
        self.label_8.setText(_translate("Form", "场地编号"))
        self.label_9.setText(_translate("Form", "场地位置"))
        self.label_10.setText(_translate("Form", "场地容量"))
        self.label_11.setText(_translate("Form", "考试编号"))
        self.addExamButton.setText(_translate("Form", "确认添加"))
        self.label_12.setText(_translate("Form", "考试场地"))
        self.label_13.setText(_translate("Form", "添加考试"))
        self.label_14.setText(_translate("Form", "考试时间"))
        self.presClassButton.setText(_translate("Form", "确认预约"))
        self.label_15.setText(_translate("Form", "课程预约"))
        self.label_16.setText(_translate("Form", "学员编号"))
        self.label_17.setText(_translate("Form", "课程编号"))
        self.label_18.setText(_translate("Form", "考试预约"))
        self.presExamButton.setText(_translate("Form", "确认预约"))
        self.label_19.setText(_translate("Form", "课程编号"))
        self.label_20.setText(_translate("Form", "场地编号"))
        self.label_21.setText(_translate("Form", "预约时间"))
        self.label_22.setText(_translate("Form", "场地编号"))
        self.label_23.setText(_translate("Form", "学员编号"))
        self.label_24.setText(_translate("Form", "教练编号"))
        self.label_25.setText(_translate("Form", "场地预约"))
        self.label_26.setText(_translate("Form", "学员编号"))
        self.presFieldButton.setText(_translate("Form", "确认预约"))
        self.addLessButton.setText(_translate("Form", "确认添加"))
        self.label_27.setText(_translate("Form", "考试编号"))
        self.label_28.setText(_translate("Form", "添加课程"))
        self.label_29.setText(_translate("Form", "我的预约"))
        self.label_30.setText(_translate("Form", "学员编号"))
        self.consult.setText(_translate("Form", "查询"))
        self.label_31.setText(_translate("Form", "预约时间"))
        self.cancel.setText(_translate("Form", "取消"))
        self.label_32.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">驾校管理系统</span></p></body></html>"))
        self.label_33.setText(_translate("Form", "Designed by liu wenbo in NWPU"))
        self.label_34.setText(_translate("Form", "All rights reserved"))
        self.addFieldButton.setText(_translate("Form", "确认添加"))
        self.dispCoach.setText(_translate("Form", "显示所有教练信息"))
        self.dispStd.setText(_translate("Form", "显示所有学员信息"))
        self.dispLess.setText(_translate("Form", "显示所有课程信息"))
        self.dispExam.setText(_translate("Form", "显示所有考试信息"))
        self.dispField.setText(_translate("Form", "显示所有场地信息"))
        self.dispBatchLess.setText(_translate("Form", "显示每批上课统计信息"))
        self.dispBatchExam.setText(_translate("Form", "显示每批考试统计信息"))
